name: Selenium Java CI - NGUYEN QA VETSPIRE

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine

    steps:
    - uses: actions/checkout@v2 # Checkout the code
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 # Setup JAVA
      with:
        java-version: 1.8
    - name: Install Google Chrome # Using shell script to install Google Chrome
      run: |
       chmod +x ./scripts/InstallChrome.sh
        ./scripts/InstallChrome.sh
    - name: Maven clean
      run: mvn clean  # give permission to Gradle to run the commands
    - name: Regression Testing
      run: mvn test # give permission to Gradle to run the commands
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Test Report            # Name of the check run which will be created
        path: "**/surefire-reports/TEST-*.xml"
        reporter: java-junit        # Format of test results
